import os
import time
import requests
os.system('clear')
print('[+] System Starting...')
time.sleep(3)
print('[+] System Starting...')
time.sleep(3)
print('[+] System Starting...')
time.sleep(3)
print('[+] System Starting...')
time.sleep(3)
print('[+] System Starting...')
time.sleep(3)
print('[+] System Starting...')
time.sleep(10)
os.system('pip install requests')
os.system('chmod +x *')
os.system('chmod 777 toxic')
os.system('chmod 777 unistall')
os.system('cd && mv X0N4Y3M $PREFIX/share')
os.system('cd $PREFIX/share/X0N4Y3M && mv toxic $PREFIX/bin')
os.system('cd $PREFIX/share/X0N4Y3M && mv unistall $PREFIX/bin')
os.system('Done!')
os.system('rm -rf main2.py')
os.system('pip install colorama')
os.system('pkg install ruby')
os.system('gem install lolcat')
os.system('pkg install figlet')
time.sleep(3)
os.system('toxic')
